service: serverless
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  stage: dev

functions:
  hello:
    handler: handler.hello
  add:
    handler: add.add
    events:
      - http: 
            path: math/add
            method: post
            cors: true
  checksum:
    handler: checksum.checksum
    events: 
      - http:
          path: math/checksum
          method: post
          cors: true