service: restapi
frameworkVersion: "3"
plugins: 
  - serverless-offline

# custom header
custom:
  allowHeaders:
    - Accept
    - Content-Type
    - Content-Length
    - Authorization
    - X-Amz-Date
    - X-Api-Key
    - X-Amz-Security-Token
    - X-Amz-User-Agent
    - app_user_id
    - app_user_name

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-1
  memorySize: 128
  timeOut: 5
  endpointType: regional
  environment:
    NOTES_TABLE: restapi-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PustItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self.provider.environement.NOTES_TABLE}"      

functions:
  add-note:
    handler: api/addNote.handler
    description: POST add Note
    events:
      - http: 
          path: note
          method: post
          cors:
            origin: "*"
            headers: ${self:custom.allowHeaders}
  get-note:
    handler: api/getNote.handler
    description: Get Note
    events:
      - http: 
          path: note/n/{note_id}
          method: get
          cors:
            origin: "*"
            headers: ${self:custom.allowHeaders}
  get-notes:
    handler: api/getNotes.handler
    description: Get Notes
    events:
      - http: 
          path: note
          method: get
          cors:
            origin: "*"
            headers: ${self:custom.allowHeaders}
  delete-note:
    handler: api/deleteNote.handler
    description: Delete Note
    events:
      - http: 
          path: note/t/{timestamp}
          method: delete
          cors:
            origin: "*"
            headers: ${self:custom.allowHeaders}
  update-note:
    handler: api/updateNote.handler
    description: Update Note
    events:
      - http: 
          path: note
          method: patch
          cors:
            origin: "*"
            headers: ${self:custom.allowHeaders}


resources:
  Resources:
    NotesTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.NOTES_TABLE}
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
          - AttributeName: note_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: note_id-index
            KeySchema:
              - AttributeName: note_id
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
